-- DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS article;

-- CREATE TABLE user (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   username TEXT UNIQUE NOT NULL,
--   password TEXT NOT NULL
-- );

CREATE TABLE article (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
--   author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL UNIQUE,
  body TEXT NOT NULL,
  summary TEXT
--   FOREIGN KEY (author_id) REFERENCES user (id)
);
